Do not crash when idling resources are in an illegal state
Using the composer while the device was lagging heavily, I've got to a
state where the following exception crashed the app:
> java.lang.IllegalArgumentException: Invalid state: idle resource count is not greater than 0.
>                                                                                                     	at ch.protonmail.android.test.idlingresources.AtomicIntegerIdlingResource.decrement(AtomicIntegerIdlingResource.kt:43)
>                                                                                                     	at ch.protonmail.android.mailcomposer.presentation.viewmodel.ComposerViewModel$submit$1.invokeSuspend(ComposerViewModel.kt:234)

which is triggered by the below "require". While this shouldn't happen
under normal condition, idling resources shouldn't impact production
usage of the app: here we log the failure and do nothing instead.

MAILANDR-952